Add links and blog content for SDS
OpenManufacturingPlatform/openmanufacturingplatform.github.io pull request #8
Opened 2022-11-29 18:53 UTC by jpradocueva

This Pull Request adds blogs and links from the home page to the new blogs.

Please review and feel free to update as you see fit.

> Note, Elizabeth Rose is still working in new blogs that I will add once it has been published.

2022-12-01 09:26 UTC, atextor requested changes

2022-12-01 09:26 UTC, atextor commented on index.md
> +[Semantic Data Structuring](https://github.com/OpenManufacturingPlatform/openmanufacturingplatform.github.io/raw/master/docs/sds/OMP-Semantic-Data-Structuring-Whitepaper.pdf) | [Industry 4.0 Core Inf
Replace the `,` after the I40 Core Information Model with ` | `

2022-12-02 13:02 UTC, BirgitBoss commented
Great, looks good. The only thing I miss are the blogs for the whitepapers
For SDS:
https://open-manufacturing.org/blog/2021/09/08/blog-manufacturing-challenges-solved-by-semantic-data-structuring/

I wonder that I do not find a blog for the i4.0 whitepaper...

2022-12-02 13:04 UTC, BirgitBoss requested changes
the changes are all ok
see only comment on missing whitepaper blogs

2022-12-03 01:40 UTC, jpradocueva commented
@BirgitBoss, I am merging the PR, and then I will create a new PR to address any missing blog.

2022-12-03 01:40 UTC, merged

2022-12-04 16:58 UTC, BirgitBoss commented
Yes, this is fine with me